### ISSUE TITLE
Pypi should update to https://pypi.org

### ISSUE THREAD

**Issue by weaming** [willfarrell/alfred-pkgman-workflow#136]

**Comment by rafenden** [comment]
PyPi search doesn't work.

![image](https://user-images.githubusercontent.com/4199239/53700832-62c37c00-3dee-11e9-8386-d6dda95f1fd0.png)

**Comment by AdamWagner** [comment]
The html of the search results page changed. `Pypi.php` is searching for `<tr>`, but the current search results are `<li>`. I briefly attempted fixing this, but was unable.

Changes are needed to line 24 (linked) and 35:
https://github.com/willfarrell/alfred-pkgman-workflow/blob/master/src/Pypi.php#L24

**Comment by jeffbyrnes** [comment]
I took a stab at this today, but wasn’t able to get it working either. Scraping a website is tricky stuff, and it’s a shame that PyPi doesn’t provide a search API as far as I could find.

**Comment by drrlvn** [comment]
Don't know if it helps but looks like there's an XML-RPC API for searching: https://warehouse.pypa.io/api-reference/xml-rpc/#package-querying (see `search(...)`).

**Comment by yamada-github-account** [comment]
I made a PR to fix web scraping syntax. (#148)

I didn't use the XML-RPC API, mentioned by @drrlvn, because the API seems to be deprecated in the (near?) future, even though (a kind of) official tool [pip still uses](https://github.com/pypa/pip/blob/89d8cba55bddfa31ce69d021c79f9997c616f723/src/pip/_internal/commands/search.py#L78-L80) the API.




> The XML-RPC API will be deprecated in the future. Use of this API is not recommended, and existing consumers of the API should migrate to the RSS and/or JSON APIs instead.
> 
> Users of this API are strongly encouraged to subscribe to the pypi-announce mailing list for notices as we begin the process of removing XML-RPC from PyPI.
> 
https://warehouse.pypa.io/api-reference/xml-rpc/
